# frozen_string_literal: true

source "https://rubygems.org"

gem "cucumber"
gem 'capybara', '3.31'
gem "httparty"
gem 'selenium-webdriver', '3.142.7'
gem 'site_prism', '3.4.2'
gem "ffi"
gem "rspec"
gem "report_builder"


